[unix_http_server]
file=/tmp/supervisor.sock
chmod=0600

[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[program:scheduler]
command=/usr/bin/php8.5 /var/www/html/artisan schedule:work --no-interaction
directory=/var/www/html
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:queue]
command=/usr/bin/php8.5 /var/www/html/artisan queue:work --sleep=3 --tries=3 --max-time=3600 --no-interaction
directory=/var/www/html
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopwaitsecs=3600
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
